version: '2'

services:
  h2o:
    build: ./h2o
    networks:
      - void
    volumes:
      - ./h2o:/h2o:ro
      - ../secrets/tls:/tls:ro
      - ../secrets/letsencrypt/:/letsencrypt/:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 80
      - 443
    environment:
      TCP_PORTS: "80, 443"
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 900000

  varnish:
    build: ./varnish
#  image: 0fc0a9a4272a
    networks:
      - void
    links:
      - ruleproxy
    volumes:
      - ./varnish:/etc/varnish
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 80
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 900000

  parsoid:
    image: thenets/parsoid:0.9.0
    networks:
      - void
    environment:
      - PARSOID_DOMAIN_psychonaut=http://varnish/w/api.php
    volumes:
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 8000
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 900000

  heimdal:
    build: ./heimdal
    networks:
      - void
    volumes:
      - ../db/heimdal:/tmp/data/
    expose:
      - 80
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 900000

  mysql:
    image: mysql:8.0.12
    networks:
      - void
    volumes:
      - ../db/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - ../backup/mysql:/backup
    expose:
      - 3306
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 900000

  postgres:
    image: postgres:11-beta3-alpine
    networks:
      - void
    environment:
      - POSTGRES_USER=mediawiki
      - POSTGRES_PASSWORD=ae69c1af8fc27ab60bc7a545
    volumes:
      - ../db/postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - ../backup/postgres:/backup
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 900000

  ### PLEBISCITE ###
  #
  # mongo-dmt:
  #   image: mongo:3.4.6
  #   networks:
  #     - void
  #   volumes:
  #     - ../db/mongo-dmt:/data/db
  #     - /etc/localtime:/etc/localtime:ro
  #   expose:
  #     - 27017
  #   restart: always
  #   ulimits:
  #     nproc: 65535
  #     nofile:
  #       soft: 800000
  #       hard: 900000

  es:
    image: elasticsearch:5.6.10
    networks:
      - void
    volumes:
      - ../db/esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 9200
      - 9300
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 900000

  redis:
    image: redis:4.0.11-alpine
    networks:
      - void
    volumes:
      - ../db/redis:/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 900000

  changebot:
    build: ./changebot
    networks:
      - void
    expose:
      - 3000
    environment:
      - TELEGRAM_TOKEN=REMOVED
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 200000

  katharsis:
    build: ./katharsis
    networks:
      - void
    expose:
      - 80
    environment:
      - API_TOKEN=REMOVED
      - APP_ID=REMOVED
      - ROCKET_ENV=prod
      - ROCKET_PORT=80
      - ROCKET_ADDRESS=0.0.0.0
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 200000

  # sociopata:
  #   build: ./sociopata/sociopata
  #   networks:
  #     - void
  #   expose:
  #     - 80
  #   environment:
  # #     - RUST_URL=redis://redis-sociopata/
  #     - ROCKET_ENV=prod
  #     - ROCKET_PORT=80
  #     - ROCKET_ADDRESS=0.0.0.0
  #   restart: always
  #   ulimits:
  #     nproc: 65535
  #     nofile:
  #       soft: 200000
  #       hard: 200000

  haproxy-hhvm:
    image: dockercloud/haproxy:latest
    depends_on:
      - mediawiki-hhvm
    networks:
      - void
    links:
      - mediawiki-hhvm
    expose:
      - 80
    ports:
      - "127.0.0.1:11936:1936"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    environment:
#      SERVICE_PORTS: 80

  haproxy-h2o:
    image: dockercloud/haproxy:latest
    depends_on:
      - h2o
    networks:
      - void
    links:
      - h2o
    expose:
      - 80
      - 443
    ports:
      - "127.0.0.1:1936:1936"
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mediawiki-hhvm:
    build: ./hhvm-base
#    image: 32ae5f4cedd0
    command: ["/usr/bin/hhvm", "-m", "server", "-c", "/etc/hhvm/server.ini", "-c", "/etc/hhvm/site.ini", "-v", "Server.AllowRunAsRoot=1"]
    networks:
      - void
    links:
      - mysql
      - redis
    volumes:
      - ../mediawiki-data:/var/www/public
      - ../cache/hhvm-tmp:/var/tmp
      - ../cache/hhvm-run:/run/hhvm
      - /etc/localtime:/etc/localtime:ro
      - ./hhvm-base/hhvm:/etc/hhvm
    expose:
      - 80
    environment:
      TCP_PORTS: "80"
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 200000

  ruleproxy:
    #image: nginx:1.15.2-alpine
    build: ./nginx/pagespeed
    networks:
      - void
    volumes:
      - ../mediawiki-data:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/pagespeed.conf:/etc/nginx/conf.d/pagespeed.conf:ro
      - ../cache/ngx_pagespeed:/var/cache/ngx_pagespeed
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NGINX_PAGESPEED=on
      - NGINX_PAGESPEED_IMG=on
      - NGINX_PAGESPEED_JS=on
      - NGINX_PAGESPEED_CSS=on
    expose:
      - 80
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 900000

  api:
    build: ./bifrost
    environment:
      - PORT=80
#      - PLEBISCITE=1
      - MONGO_URL=mongodb://mongo-dmt:27017/plebiscite
      - MONGO_COLLECTION=reports
      - ENGINE_API_KEY=service:bifrost:_bcIV50oaalUqT9zOQkBXw
    networks:
      - void
    expose:
      - 80
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 900000

  countly-mongo:
    image: mongo:3.4.10
    networks:
      - void
    volumes:
      - ../db/countly-mongo:/data/db
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 27017
    restart: always
    ulimits:
      nproc: 400000
      nofile:
        soft: 800000
        hard: 900000

  countly:
    image: countly/countly-server
    networks:
      - void
    links:
      - countly-mongo
    volumes:
      - ./countly/config/frontend.js:/opt/countly/frontend/express/config.js
      - ./countly/config/api.js:/opt/countly/api/config.js
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 80
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 200000

  dmt-friendly-fire:
    build: ./dmt-friendly-fire
    networks:
      - void
    environment:
      - FF_SERVICES=mediawiki-hhvm,h2o
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  i2pd:
    image: ksey/i2pd
    networks:
      - void
    volumes:
      - ../secrets/i2pd/:/var/lib/i2pd
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 200000

networks:
  void:
    ipam:
      driver: default
      config:
        - subnet: 3.2.0.0/16
          ip_range: 3.2.5.0/24
          gateway: 3.2.5.254
