version: '2'

services:
  h2o:
    build: ./h2o
    networks:
      - void
    volumes:
      - ./h2o:/h2o:ro
      - ../secrets/tls:/tls:ro
      - ../secrets/letsencrypt/:/letsencrypt/:ro
      - ../secrets/le-mind/archive:/le-mind:ro
      - ../secrets/le-gds/archive:/le-gds:ro
      - ../cache/h2o-le:/h2o-le
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 80
      - 443
    environment:
      TCP_PORTS: "80, 443"
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 900000

  varnish:
    build: ./varnish
#  image: 0fc0a9a4272a
    networks:
      - void
    links:
      - pagespeed
    volumes:
      - ./varnish:/etc/varnish
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 80
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 900000

  parsoid:
    image: thenets/parsoid:0.10
    networks:
      - void
    environment:
      - PARSOID_DOMAIN_psychonaut=http://varnish/w/api.php
    volumes:
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 8000
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 900000

  mysql:
    image: mysql:8.0.22
    networks:
      - void
    volumes:
      - ../db/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - ../backup/mysql:/backup
    expose:
      - 3306
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 900000

  backup-s3:
    image: databack/mysql-backup:0.10.0
    networks:
      - void
    restart: always
    volumes:
      - ./backup-params/psy-gla-backup.pub.pem:/scripts.d/post-backup/psy-gla-backup.pub.pem
      - ./backup-params/post-enc.sh:/scripts.d/post-backup/post-enc.sh
    environment:
      - DB_DUMP_TARGET=s3://REDACTED/mysql
      - DB_USER=REDACTED
      - DB_PASS=REDACTED
      - DB_DUMP_FREQ=60
      - DB_SERVER=mysql
      - AWS_ACCESS_KEY_ID=REDACTED
      - AWS_SECRET_ACCESS_KEY=REDACTED
      - AWS_DEFAULT_REGION=us-east-1
      - DB_DUMP_KEEP_PERMISSIONS=false

  backup-loc-md0:
    image: databack/mysql-backup:0.10.0
    networks:
      - void
    restart: always
    volumes:
      - /backup/dmt/db/mysql:/db
      - ./backup-params/psy-gla-backup.pub.pem:/scripts.d/post-backup/psy-gla-backup.pub.pem
      - ./backup-params/post-enc.sh:/scripts.d/post-backup/post-enc.sh
    environment:
      - DB_DUMP_TARGET=/db
      - DB_USER=mediawiki
      - DB_SERVER=REDACTED
      - DB_PASS=REDACTED
      - DB_DUMP_FREQ=60
      - DB_DUMP_KEEP_PERMISSIONS=false

  ### PLEBISCITE ###
  #
  # mongo-dmt:
  #   image: mongo:3.4.6
  #   networks:
  #     - void
  #   volumes:
  #     - ../db/mongo-dmt:/data/db
  #     - /etc/localtime:/etc/localtime:ro
  #   expose:
  #     - 27017
  #   restart: always
  #   ulimits:
  #     nproc: 65535
  #     nofile:
  #       soft: 800000
  #       hard: 900000

  es:
    image: elasticsearch:6.8.13
    networks:
      void:
        ipv4_address: 3.2.5.100
    volumes:
      - ../db/esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 9200
      - 9300
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 900000

  redis:
    image: redis:6.0.9-alpine
    networks:
      - void
    volumes:
      - ../db/redis:/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 900000

################ APM ##########################

#  apm-delete-indexes:
#    image: playdingnow/delete-outdated-es-indexes:1.3
#    networks:
#      - void
#    environment:
#      - eshost=elasticsearch
#      - esport=9200
#      - esmaxdays=15
#    restart: always
#    ulimits:
#      nproc: 65535
#      nofile:
#        soft: 800000
#        hard: 900000
#
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
#    networks:
#      - void
#    environment:
#      - ES_JAVA_OPTS=-Xms512m -Xmx512m
#    volumes:
#      - ../db/apm/es:/usr/share/elasticsearch/data
#      - /etc/localtime:/etc/localtime:ro
#    expose:
#      - 9200
#      - 8200
#    restart: always
#    ulimits:
#      nproc: 65535
#      nofile:
#        soft: 800000
#        hard: 900000
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:6.3.0
#    networks:
#      - void
#    volumes:
#      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
#    expose:
#      - 5601
#    restart: always
#    ulimits:
#      nproc: 65535
#      nofile:
#        soft: 800000
#        hard: 900000
#
#  apmserver:
#    image: playdingnow/elastic-apm-server:1.6.0
#    networks:
#      - void
#    restart: always
#    expose:
#      - 8200
#    ulimits:
#      nproc: 65535
#      nofile:
#        soft: 800000
#        hard: 900000

###############################################

  changebot:
    build: ./changebot
    networks:
      - void
    expose:
      - 3000
    environment:
      - TELEGRAM_TOKEN=REDACTED
      - RUST_BACKTRACE=1
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 200000

  katharsis:
    build: ./katharsis
    networks:
      - void
    expose:
      - 80
    environment:
      - API_TOKEN=REDACTED
      - APP_ID=REDACTED
      - ROCKET_ENV=prod
      - ROCKET_PORT=80
      - ROCKET_ADDRESS=0.0.0.0
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 200000

  # sociopata:
  #   build: ./sociopata/sociopata
  #   networks:
  #     - void
  #   expose:
  #     - 80
  #   environment:
  # #     - RUST_URL=redis://redis-sociopata/
  #     - ROCKET_ENV=prod
  #     - ROCKET_PORT=80
  #     - ROCKET_ADDRESS=0.0.0.0
  #   restart: always
  #   ulimits:
  #     nproc: 65535
  #     nofile:
  #       soft: 200000
  #       hard: 200000

#  haproxy-hhvm:
#    image: dockercloud/haproxy:latest
#    depends_on:
#      - mediawiki-hhvm
#    networks:
#      - void
#    links:
#      - mediawiki-hhvm
#    expose:
#      - 80
#    ports:
#      - "127.0.0.1:11936:1936"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    environment:
#      SERVICE_PORTS: 80

  haproxy-h2o:
    image: dockercloud/haproxy:latest
    depends_on:
      - h2o
    networks:
      - void
    links:
      - h2o
    expose:
      - 80
      - 443
    ports:
      - "127.0.0.1:1936:1936"
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#  mediawiki-hhvm:
#    build: ./hhvm-base
#    image: 32ae5f4cedd0
#    command: ["/usr/bin/hhvm", "-m", "server", "-c", "/etc/hhvm/server.ini", "-c", "/etc/hhvm/site.ini", "-v", "Server.AllowRunAsRoot=1"]
#    networks:
#      - void
#    links:
#      - mysql
#      - redis
#    volumes:
#      - ../mediawiki-data:/var/www/public
#      - ../cache/hhvm-tmp:/var/tmp
#      - ../cache/hhvm-run:/run/hhvm
#      - /etc/localtime:/etc/localtime:ro
#      - ./hhvm-base/hhvm:/etc/hhvm
#    expose:
#      - 80
#    environment:
#      TCP_PORTS: "80"
#    restart: always
#    ulimits:
#      nproc: 65535
#      nofile:
#        soft: 200000
#        hard: 200000

  php-fpm:
    build: ./phpfpm
    networks:
      - void
    volumes:
      - ../mediawiki-data:/var/www/public
      - ../cache/phpfpm:/cache
      - ../cache/mediawiki:/var/tmp/mediawiki
      - /dev/null:/var/log/lua.log
    restart: always
    ulimits:
      nproc: 400000
      nofile:
        soft: 800000
        hard: 900000

  pagespeed:
    build: ./pagespeed/pagespeed
    networks:
      - void
    volumes:
      - ../mediawiki-data:/var/www/public
      - ./pagespeed/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./pagespeed/pagespeed.conf:/etc/nginx/conf.d/pagespeed.conf:ro
      - ../cache/ngx_pagespeed:/var/cache/ngx_pagespeed
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NGINX_PAGESPEED=on
      - NGINX_PAGESPEED_IMG=on
      - NGINX_PAGESPEED_JS=on
      - NGINX_PAGESPEED_CSS=on
    expose:
      - 80
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 900000

  ruleproxy:
    build: ./ruleproxy/pagespeed
    networks:
      - void
    volumes:
      - ../mediawiki-data:/var/www/public
      - ./ruleproxy/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 80
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 900000

  api:
    build: ./bifrost
    environment:
      - PORT=80
#      - PLEBISCITE=1
      - MONGO_URL=mongodb://mongo-dmt:27017/plebiscite
      - MONGO_COLLECTION=reports
      - ENGINE_API_KEY=REDACTED
#      - useAPM=1
      - apmKey=REDACTED
      - apmServer=http://apmserver:8200
    networks:
      - void
    expose:
      - 80
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 900000

  countly-mongo:
    image: mongo:4.2.0
    networks:
      - void
    volumes:
      - ../db/countly-mongo:/data/db
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 27017
    restart: always
    ulimits:
      nproc: 400000
      nofile:
        soft: 800000
        hard: 900000

  countly:
    image: countly/countly-server:20.04.1.7
    networks:
      - void
    links:
      - countly-mongo
    volumes:
      - ./countly/config/frontend.js:/opt/countly/frontend/express/config.js
      - ./countly/config/api.js:/opt/countly/api/config.js
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 80
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 200000

  dmt-friendly-fire:
    build: ./dmt-friendly-fire
    networks:
      - void
    environment:
      - FF_SERVICES=mediawiki-hhvm,h2o
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  i2pd:
    image: ksey/i2pd
    networks:
      - void
    volumes:
      - ../secrets/i2pd/:/var/lib/i2pd
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 200000

networks:
  void:
    ipam:
      driver: default
      config:
        - subnet: 3.2.0.0/16
          ip_range: 3.2.5.0/24
          gateway: 3.2.5.254
